<?php $this->layout('template', $detail) ?>

<?php $this->start('home') ?>
<!-- start: Wrapper -->	
<div id="wrapper">		

    <!-- start: Container -->	
    <div class="container">

        <!-- start: Row -->
        <div class="row">
            <div class="span8 main-container">
                <?php foreach($data as $val):?>
                <div class="content-container">
                    <div class="post-container">
                        <h2><?=$val['judul']?></h2><br>
                        <div class="img-container">
                            <?php 
                            if(empty($val['image'])){
                                $gambar = get_site_url() . '/img/default-image.png';
                            } else {
                                $gambar = get_site_url() . '/asset/post_image/'.$val['image'];
                            }
                            ?>
                            <img src="<?=$gambar?>">
                        </div>
                    </div>
                    <div class="post-tool">
                        <ul class="social-bookmarks ">
                            <li class="facebook" title="Share"><a href="javascript:fbshareCurrentPage(<?=$val['post_id']?>)" target="_blank">facebook</a></li>
                            <li class="twitter" title="Tweet"><a href="http://twitter.com/share?url=<?=$detail['baseUrl'].$val['post_id']?>" target="_blank">twitter</a></li>
                        </ul>
                        <a href="" class="like" title="Suka"><i class="ico-thumbs-up  ico-white circle-color-full small-color"></i></a>
                        <a href="" class="like" title="Tidak Suka"><i class="ico-thumbs-down  ico-white circle-color-full small-color"></i></a>
                        <a href="" class="like" title="Komentar"><i class="ico-chat ico-white circle-color-full small-color"></i></a>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>
            <!-- sidebar ads start-->
            <div class="span4">
                <div id="sidebar">
                        <div class="ads-one">
                            <script type="text/javascript"><!--
                            google_ad_client = "ca-pub-9634676781117222";
                            /* 300x250, created 9/4/10 */
                            google_ad_slot = "2205194959";
                            google_ad_width = 300;
                            google_ad_height = 250;
                            //-->
                            </script>
                            <script type="text/javascript"
                            src="//pagead2.googlesyndication.com/pagead/show_ads.js">
                            </script>
                        </div>
                        <div id="ads-two">
                            <script type="text/javascript"><!--
                            google_ad_client = "ca-pub-9634676781117222";
                            /* 300x250, created 9/4/10 */
                            google_ad_slot = "2205194959";
                            google_ad_width = 300;
                            google_ad_height = 250;
                            //-->
                            </script>
                            <script type="text/javascript"
                            src="//pagead2.googlesyndication.com/pagead/show_ads.js">
                            </script>
                        </div>
                </div>
            </div>
            <!-- sidebar ads end-->
            <script language="javascript">
                function fbshareCurrentPage(id_post)
                {window.open("https://www.facebook.com/sharer/sharer.php?u="+escape(window.location.href)+id_post+"&t=" +document.title, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false; }

                $(document).ready(function() {
                    var s = $("#ads-two");
                    var pos = s.position();                   
                    $(window).scroll(function() {
                        var windowpos = $(window).scrollTop();
                       
                            if (windowpos+55 >= pos.top) {
                                s.addClass("ads-two");
                            } else {
                                s.removeClass("ads-two");
                            }
                        });
                });
            </script>

        </div>
        <!-- end: Row -->

    </div>
    <!-- end: Container -->

</div>
<!-- end: Wrapper  -->
<?php $this->stop() ?>
