<!DOCTYPE html>
<html lang="en">
<head>
	<!-- start: Meta -->
	<meta charset="utf-8">
	<title>Login- NgakakSeru</title> 
	<meta name="description" content="Ngakak Seru Website Lucu"/>
	<meta name="keywords" content="fun,funny,lol,meme,GIF,wtf,omg,fail,video,cosplay,geeky,forever alone" />
	<meta name="author" content="DDA Academy"/>
	<!-- end: Meta -->
	
	<!-- start: Mobile Specific -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<!-- end: Mobile Specific -->
	
	<!-- start: Facebook Open Graph -->
	<meta property="og:title" content=""/>
	<meta property="og:description" content=""/>
	<meta property="og:type" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:image" content=""/>
	<!-- end: Facebook Open Graph -->

    <!-- start: CSS -->
    <link href="<?=get_site_url();?>main/css/bootstrap.css" rel="stylesheet">
    <link href="<?=get_site_url();?>main/css/bootstrap-responsive.css" rel="stylesheet">
	<link href="<?=get_site_url();?>main/css/style.css" rel="stylesheet">
    <link href="<?=get_site_url();?>main/css/custom.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700">
	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Droid+Serif">
	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Boogaloo">
	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Economica:700,400italic">
	<link href="<?=get_site_url();?>main/img/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
	<!-- end: CSS -->

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

</head>
<body>
	
	<!--start: Header -->
	<header>	
	<!DOCTYPE HTML>
		<!--start: Container -->
		<div class="container">
			
			<!--start: Row -->
			<div class="row">
					
				<!--start: Logo -->
				<div class="logo span3">
						
					<a class="brand" href="<?=get_site_url();?>"><img src="<?=get_site_url();?>main/img/logo.jpg" style="height:35px;max-width:none;"></a>
						
				</div>
				<!--end: Logo -->
					
				<!--start: Navigation -->
				<div class="span9">
						
					<div class="navbar navbar-inverse">
			    		<div class="navbar-inner">
			        		<div class="container">
			          			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
			            			<span class="icon-bar"></span>
			            			<span class="icon-bar"></span>
			            			<span class="icon-bar"></span>
			          			</a>
			          			<div class="nav-collapse collapse">
			            			<ul class="nav">
			                  			<li><a href="login">Masuk</a></li>
	                                    <li><a href="register">Daftar</a></li>
	                                    <li class="red-btton" title="upload"><a href="#"><img src="<?= get_site_url(); ?>main/img/upload.png" width="26px" height="auto"/> Upload</a></li>
			            			</ul>
			          			</div>
			        		</div>
			      		</div>
			    	</div>
					
				</div>	
				<!--end: Navigation -->
                
			</div>
			<!--end: Row -->
			
		</div>
		<!--end: Container-->			
	</header>
	<!--end: Header-->

	<!-- start: Wrapper -->	
	<div id="wrapper">		

		<!-- start: Container -->	
		<div class="container">
			
			<!-- start login -->
			<div class="row">
				<div class="login">
				<div>
		        <div class="header" >
		            <h1>Silahkan Login :</h1>
		        </div>
                <?php if (!empty($message)): ?>
                <div class="row">
                    <div class="alert alert-danger" role="alert">
                        <?= $this->e($message) ?>
                    </div>
                </div>
                <?php endif; ?>

		            <form action="<?=get_site_url();?>auth/login" method="POST">
		                <ul>
		                    <div class="form-login">
		                        <li><input type="text" value="<?= (!empty($username))?$username:'' ?>" placeholder="Username" name="username" id="url" required/><img id="url_user" 
		                        src="<?=get_site_url();?>main/img/user.png" alt=""></li>
		                        <li> <input type="password"  placeholder="Password" name="password" id="url" required/><img id="url_password" src="<?=get_site_url();?>main/img/passicon.png" alt=""></li>
		                        <h5><a href="#" class="forgot-password">I forgot my Password!</a></h5>
		                            <input type="submit"  value="Login" >
		                    </div>	
		                </ul>
		            </form>
		            </div>
                </div>
        <!-- end of login -->
		</div> <!-- end: Container -->
  	</div>
	<!-- end: Wrapper  -->			
	</div>
<!-- start: Java Script -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="<?=get_site_url();?>main/js/jquery-1.8.2.js"></script>
<script src="<?=get_site_url();?>main/js/bootstrap.js"></script>
<script src="<?=get_site_url();?>main/js/flexslider.js"></script>
<script src="<?=get_site_url();?>main/js/carousel.js"></script>
<script src="<?=get_site_url();?>main/js/jquery.cslider.js"></script>
<script src="<?=get_site_url();?>main/js/slider.js"></script>
<script def src="<?=get_site_url();?>main/js/custom.js"></script>
<!-- end: Java Script -->

</body>
</html>
