<?php //$this->start('sidebar') ?>
<!DOCTYPE HTML>
<div class="span4">
<div id="sidebar">
    <div class="ads-one">
        <script type="text/javascript"><!--
            google_ad_client = "ca-pub-9634676781117222";
            /* 300x250, created 9/4/10 */
            google_ad_slot = "2205194959";
            google_ad_width = 300;
            google_ad_height = 250; //-->
        </script>
        <script type="text/javascript"src="//pagead2.googlesyndication.com/pagead/show_ads.js"></script>
    </div>
    <div id="ads-two">
            <script type="text/javascript"><!--
                google_ad_client = "ca-pub-9634676781117222";
                /* 300x250, created 9/4/10 */
                google_ad_slot = "2205194959";
                google_ad_width = 300; 
                google_ad_height = 250;//-->
            </script>
            <script type="text/javascript" src="//pagead2.googlesyndication.com/pagead/show_ads.js"></script>
    </div>
</div>
    <h2>Subscribe</h2>
    <input type="text" name="subcribe" class="form-control">
    <button class="btn btn-default btn-md">Subscribe</button>
    <br><br>
    <h2>Get The App</h2>
    <button class="btn btn-default">DOWNLOAD</button>
    <br><br>
    <div id="footer">
        <a href="">Pasang Iklan</a> · <a href="">Kontak</a> · <a href="">Privasi</a> · <a href="">Peraturan</a>
        <br>
        www.NgakakSeru.com © 2014</a>
    </div>
</div>
<?php //$this->stop() ?>