<html>
    <head>
        <meta charset="utf-8">
        <title><?= $this->e($title) ?></title>
        <meta name="description" content="<?= $this->e($description) ?>"/>
        <meta name="keywords" content="<?= $this->e($keywords) ?>" />
        <meta name="author" content="<?= $this->e($author) ?>"/>
        <!-- end: Meta -->

        <!-- start: Mobile Specific -->
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <!-- end: Mobile Specific -->

        <!-- start: Facebook Open Graph -->
        <meta property="og:title" content=""/>
        <meta property="og:description" content=""/>
        <meta property="og:type" content=""/>
        <meta property="og:url" content=""/>
        <meta property="og:image" content=""/>
        <!-- end: Facebook Open Graph -->

        <!-- start: CSS -->
        <link href="<?= get_site_url(); ?>main/css/bootstrap.css" rel="stylesheet">
        <link href="<?= get_site_url(); ?>main/css/bootstrap-responsive.css" rel="stylesheet">
        <link href="<?= get_site_url(); ?>main/css/style.css" rel="stylesheet">
        <link href="<?= get_site_url(); ?>main/css/custom.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700">
        <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Droid+Serif">
        <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Boogaloo">
        <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Economica:700,400italic">
        <link href="<?= get_site_url(); ?>main/img/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
        <!-- end: CSS -->

        <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

    </head>
    <body>
        <!-- Script Sosial Follow-->
        <script type="text/javascript">
                            window.twttr = (function (d, s, id) {
                              var t, js, fjs = d.getElementsByTagName(s)[0];
                              if (d.getElementById(id)) return;
                              js = d.createElement(s); js.id = id;
                              js.src= "https://platform.twitter.com/widgets.js";
                              fjs.parentNode.insertBefore(js, fjs);
                              return window.twttr || (t = { _e: [], ready: function (f) { t._e.push(f) } });
                            }(document, "script", "twitter-wjs"));
        </script>
        <script src="https://apis.google.com/js/platform.js" async defer>
          {lang: 'id'}
        </script>
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/id_ID/sdk.js#xfbml=1&version=v2.0";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
        <!-- End Script Sosial Follow-->

        <header>
            <!--start: Container -->
            <div class="container">
                <!-- start: Row -->
                <div class="row">
                    <!--start: Logo -->
                    <div class="logo span3">

                        <a class="brand" href="<?= get_site_url(); ?>"><img src="<?= $baseUrl; ?>/img/logo.jpg" style="height:35px;max-width:none;"></a>

                    </div>
                    <!--end: Logo -->

                    <!--start: Navigation -->
                    <div class="span9">

                        <div class="navbar navbar-inverse" id="user-menu">
                            <div class="navbar-inner">
                                <div class="container">
                                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </a>
                                    <div class="nav-collapse collapse">
                                        <ul class="nav">
                                            <?php if ($app['auth']->hasIdentity()): ?>
                                            <li><a href="auth/logout">Keluar (<?= $this->e($app['auth']->getIdentity()) ?>)</a></li>
                                            <?php else: ?>
                                            <li><a href="auth/login">Masuk</a></li>
                                            <?php endif; ?>
                                            <li><a href="auth/register">Daftar</a></li>
                                            <li class="red-btton" title="upload"><a href="#"><img src="<?= $baseUrl; ?>/img/upload.png" width="26px" height="auto"/> Upload</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>	
                    <!--end: Navigation -->
                </div>
                <!-- end: Row -->
            </div>
        </header>
    	<div id="botom-header">
	    	<div class="container">
	            	<!-- start: Row -->
	            <div class="row header-bottom-left">
		            	<div class="webite-name-bottom-header">
		            		Ngakak Seru, Santai aja kali
		            	</div>
                        
                        <div class="twitter-button">
    							<a class="twitter-follow-button"
    							  href="https://twitter.com/ngakakseru_com"
    							  data-show-count="true"
    							  data-lang="id">
    							ikuti @ngakakseru_com
    							</a>
    				    </div>
                        <div class="facebook-button">
                            <div class="fb-like" data-href="https://www.facebook.com/pages/Ngakak-Seru-Com/764408660306405" data-layout="button_count" data-action="like" data-show-faces="true" data-share="false"></div>
                        </div>
                        <div class="goole-plus-button">
                            <div class="g-follow" data-annotation="bubble" data-height="20" data-href="https://plus.google.com/113719268903974888898" data-rel="author"></div>
                        </div>
				</div>
	                <!-- end: Row -->
	        </div>
        </div>
        <?= $this->section($layout) ?>

        <!-- start: Java Script -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="<?= get_site_url(); ?>main/js/jquery-1.8.2.js"></script>
        <script src="<?= get_site_url(); ?>main/js/bootstrap.js"></script>
        <script src="<?= get_site_url(); ?>main/js/flexslider.js"></script>
        <script src="<?= get_site_url(); ?>main/js/carousel.js"></script>
        <script src="<?= get_site_url(); ?>main/js/jquery.cslider.js"></script>
        <script src="<?= get_site_url(); ?>main/js/slider.js"></script>
        <script def src="<?= get_site_url(); ?>main/js/custom.js"></script>
        
        <!-- end: Java Script -->

    </body>
</html>
